# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=42)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Regiões',
                'verbose_name': 'Regiao',
            },
        ),
    ]
