# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='nome',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
