# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20170125_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiao',
            options={'verbose_name': 'Região', 'verbose_name_plural': 'Regiões'},
        ),
        migrations.AlterField(
            model_name='cidade',
            name='ddd',
            field=models.CharField(help_text='Discagem Direta a Distância', max_length=2, verbose_name='DDD'),
        ),
    ]
